name: tenup_project
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  #State management
  provider: ^6.0.3
  
  #UI
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.0+3
  
  #Network
  url_launcher: ^6.3.1
  cached_network_image: ^3.2.0

  #API
  yelp_api:
    path: packages/yelp_api

  #Local DB
  local_db:
    path: packages/local_db
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  http_mock_adapter: ^0.6.1
  build_runner: ^2.1.2
  json_serializable: ^6.1.4
  provider_test: ^2.0.2
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/